var V = {

	WIDTH: 0,
	HEIGHT: 0,
	INFINITE: 0,
	MARGIN_HEIGHT: 0,
	MARGIN_COLOR: 0,
	BACKGROUND_NORMAL_COLOR: 0,
	ACTUAL_HEIGHT: 0,
	NUM_PLATFORMS: 0,
	PLATFORM_HEIGHT: 0,
	PLAYER_VISIBLE_COLOR: 0,
	PLAYER_HIDDEN_COLOR: 0,
	PLAYER_JUMP_SPEED_VECTOR: 0,
	PLAYER_MOVE_ACCELERATION_VECTOR: 0,
	PLAYER_MOVE_DECCELERATION_VECTOR: 0,
	PLAYER_MOVE_FRICTION: 0,
	PLAYER_DUCK_FRICTION: 0,
	GRAVITY: 0,
	SHOOTER_COLOR: 0,
	SHOOTER_Y_START: 0,
	SHOOTER_RADIUS: 0,
	SHOOTER_SHOOT_DELAY_FRAMES: 0,
	SHOOTER_FLY_DELAY_FRAMES: 0,
	SHOOTER_FRICTION: 0,
	SHOOTER_MOVE_ACCELERATE_LEFT_VECTOR: 0,
	SHOOTER_MOVE_ACCELERATE_RIGHT_VECTOR: 0,
	SHOOTER_MOVE_ACCELERATE_UP_VECTOR: 0,
	SHOOTER_MOVE_ACCELERATE_DOWN_VECTOR: 0,
	SHOOTER_MAX_SPEED: 0,
	SHOOTER_AVG_SPEED: 0,
	X_SCREEN_SPEED_PER_FRAME: 0,
	X_OBSTACLE_AVERAGE_DELTA: 0,
	X_OBSTACLE_DISPERSION_DELTA: 0,
	OBSTACLE_COLOR: 0,
	FONT_SIZE: 0,
	STARTING_FRAME_COUNT: 0,

	getPlayerPoly: function(x, y, width, height) {
		var pos = vector.create(x, y),
			model = [
				vector.create(0, 0),
				vector.create(width, -height),
				vector.create(width, 0)
			],
			color = V.PLAYER_VISIBLE_COLOR;
		return polygon.create(pos, model, color, width, height);
	},

	init: function(width, height) {
		V.WIDTH = width;
		V.HEIGHT = height;
		V.ACTUAL_HEIGHT = V.WIDTH / 10;
		V.MARGIN_HEIGHT = (V.HEIGHT - V.ACTUAL_HEIGHT) / 2;
		V.MARGIN_COLOR = "#987654";
		V.BACKGROUND_NORMAL_COLOR = "#ffffff";
		V.NUM_PLATFORMS = 6;
		V.PLATFORM_HEIGHT = V.ACTUAL_HEIGHT / V.NUM_PLATFORMS;
		V.PLAYER_VISIBLE_COLOR = "#123456";
		V.PLAYER_HIDDEN_COLOR = "#6F9A80";
		V.PLAYER_JUMP_SPEED_VECTOR = vector.create(0, -V.PLATFORM_HEIGHT / 9);
		V.PLAYER_MOVE_ACCELERATION_VECTOR = vector.create(V.PLATFORM_HEIGHT / 70, 0);
		V.PLAYER_MOVE_DECCELERATION_VECTOR = vector.create(-V.PLATFORM_HEIGHT / 70, 0);
		V.PLAYER_MOVE_FRICTION = V.PLATFORM_HEIGHT / 200;
		V.PLAYER_DUCK_FRICTION = V.PLATFORM_HEIGHT / 30;
		V.GRAVITY = V.PLATFORM_HEIGHT / 300;
		V.SHOOTER_COLOR = "#ee1231";
		V.SHOOTER_RADIUS = V.PLATFORM_HEIGHT / 4;
		V.SHOOTER_Y_START = V.HEIGHT-V.MARGIN_HEIGHT-V.SHOOTER_RADIUS-2;
		V.SHOOTER_SHOOT_DELAY_FRAMES = 100;
		V.SHOOTER_FLY_DELAY_FRAMES = 100,
		V.SHOOTER_FRICTION = V.PLATFORM_HEIGHT / 30,
		V.SHOOTER_MOVE_ACCELERATE_LEFT_VECTOR = vector.create(-V.PLATFORM_HEIGHT / 70, 0);
		V.SHOOTER_MOVE_ACCELERATE_RIGHT_VECTOR = vector.create(V.PLATFORM_HEIGHT / 70, 0);
		V.SHOOTER_MOVE_ACCELERATE_UP_VECTOR = vector.create(0, -V.PLATFORM_HEIGHT / 500);
		V.SHOOTER_MOVE_ACCELERATE_DOWN_VECTOR = vector.create(0, V.PLATFORM_HEIGHT / 500);
		V.SHOOTER_MAX_SPEED = V.WIDTH / 100;
		V.SHOOTER_AVG_SPEED = V.WIDTH / 400;
		V.X_SCREEN_SPEED_PER_FRAME = 4;
		V.X_OBSTACLE_AVERAGE_DELTA = 10;
		V.X_OBSTACLE_DISPERSION_DELTA = 100;
		V.OBSTACLE_COLOR = "#ccffaa";
		V.FONT_SIZE = 20;
		V.STARTING_FRAME_COUNT = -400;
	}

}